variables:
  triggerBranch: 'main'
  vmImage: 'ubuntu-latest'
  mavenPomFile: 'pom.xml'
  mavenOptions: '-Xmx3072m'
  jdkVersion: '11'
  jdkArch: 'x64'
  publishJUnitResults: true
  testResultsFiles: '**/surefire-reports/TEST-*.xml'
  mavenGoals: 'clean install'
  pathToPublish: 'target'
  artifactName: 'java-app'
  publishLocation: 'Container'
